---
Name: silverstripe-rollbar
After:
  - 'framework/*'
  - 'cms/*'
---

Injector:
  RollbarLogWriter:
    class: silverstripe\rollbar\writer\RollbarLogWriter

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - silverstripe\rollbar\Eollbar
